'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { randomUUID } = require('node:crypto');

/**
 * The single alert sink in this codebase.
 *
 * Ownership rule (epic #2, invariant 3): alerts are generated by the
 * verifier / dead-man watch, never by the daemon. The daemon-side code under
 * `src/daemon/` must not import this module — enforced by a test.
 *
 * Alerts are appended as JSON Lines to `filePath` (the out-of-band sink) and
 * mirrored to any in-process listeners (used by tests and supervisors).
 */
class AlertChannel {
  constructor({ filePath, emitter = 'verifier', now } = {}) {
    if (!emitter) {
      throw new Error('AlertChannel requires an emitter identity');
    }
    this.filePath = filePath || null;
    this.emitter = emitter;
    this.now = now || (() => new Date().toISOString());
    this.listeners = [];
    if (this.filePath) {
      fs.mkdirSync(path.dirname(this.filePath), { recursive: true });
    }
  }

  onAlert(listener) {
    this.listeners.push(listener);
    return this;
  }

  emit(kind, detail = {}) {
    const alert = {
      id: randomUUID(),
      ts: this.now(),
      emitter: this.emitter,
      kind,
      detail,
    };
    if (this.filePath) {
      fs.appendFileSync(this.filePath, JSON.stringify(alert) + '\n');
    }
    for (const listener of this.listeners) {
      listener(alert);
    }
    return alert;
  }
}

module.exports = { AlertChannel };
