'use strict';

const http = require('node:http');

/**
 * Transport for the external verifier.
 *
 * The daemon never touches the pipeline (or the alert channel) directly — it
 * only speaks this minimal HTTP surface. Keeping the verifier behind a
 * process boundary is what makes "alerts are generated by the verifier, not
 * the daemon" a structural property instead of a convention.
 *
 *   GET  /health        liveness
 *   POST /intent        phase 1 — submit a mutation, get an intent
 *   POST /apply         phase 2 — intent + mutation → checks → apply → log
 */

function readBody(req, maxBodyBytes) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    req.on('data', (chunk) => {
      size += chunk.length;
      if (size > maxBodyBytes) {
        reject(Object.assign(new Error('request body too large'), { statusCode: 413 }));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on('end', () => resolve(Buffer.concat(chunks)));
    req.on('error', reject);
  });
}

function send(res, statusCode, payload) {
  const body = JSON.stringify(payload);
  res.writeHead(statusCode, { 'content-type': 'application/json' });
  res.end(body);
}

async function startVerifierServer({ pipeline, host = '127.0.0.1', port = 0, maxBodyBytes = 1024 * 1024 }) {
  if (!pipeline) throw new Error('startVerifierServer requires a pipeline');

  const server = http.createServer((req, res) => {
    handle(req, res).catch((err) => {
      const status = err.statusCode || 500;
      if (!res.headersSent) send(res, status, { error: err.message });
      else res.end();
    });
  });

  async function handle(req, res) {
    const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);

    if (req.method === 'GET' && url.pathname === '/health') {
      send(res, 200, { ok: true, component: 'verifier' });
      return;
    }

    if (req.method === 'POST' && (url.pathname === '/intent' || url.pathname === '/apply')) {
      const raw = await readBody(req, maxBodyBytes);
      let body;
      try {
        body = JSON.parse(raw.toString('utf8') || '{}');
      } catch {
        send(res, 400, { error: 'invalid JSON body' });
        return;
      }

      if (url.pathname === '/intent') {
        if (!body.mutation || typeof body.mutation !== 'object') {
          send(res, 400, { error: 'mutation object is required' });
          return;
        }
        const intent = pipeline.submitIntent(body.mutation);
        send(res, 200, { intent });
        return;
      }

      if (!body.intentId || typeof body.intentId !== 'string') {
        send(res, 400, { error: 'intentId is required' });
        return;
      }
      if (!body.mutation || typeof body.mutation !== 'object') {
        send(res, 400, { error: 'mutation object is required' });
        return;
      }
      const result = await pipeline.applyIntent(body.intentId, body.mutation);
      send(res, result.applied ? 200 : 409, result);
      return;
    }

    send(res, 404, { error: 'not found' });
  }

  await new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(port, host, resolve);
  });

  const address = server.address();
  const url = `http://${host}:${address.port}`;

  return {
    server,
    url,
    port: address.port,
    close: () => new Promise((resolve) => server.close(resolve)),
  };
}

module.exports = { startVerifierServer };
